# -- Setup -- 

before_all do |lane|
  load_dotenv('.env')
end

# -- Lanes -- 

lane :beta do
  match_certificates()

  build_app(
    scheme: "GameSession",
    output_directory: "fastlane/build"
  )

  upload_to_testflight(
    api_key: generateAppstoreConnectApiKey(),
    ipa: 'fastlane/build/GameSession.ipa',
    skip_waiting_for_build_processing: true
  )
end

lane :match_certificates do
  match(
    type: "appstore",
    app_identifier: ["com.bcl.GameSession"],
    api_key: generateAppstoreConnectApiKey(),
    git_branch: "main"
  )
end

lane :match_nuke_certificates do
  match_nuke(
    type: "appstore",
    app_identifier: ["com.bcl.GameSession"],
    api_key: generateAppstoreConnectApiKey(),
    git_branch: "main"
  )
end

# -- Methods -- 

def load_dotenv(path)
  if File.file?(path)
    sh(path)
  end
end


def generateAppstoreConnectApiKey()
  return app_store_connect_api_key(
    key_id: ENV["APPLE_KEY_ID"],
    issuer_id: ENV["APPLE_ISSUER_ID"],
    key_content: ENV["APPLE_KEY_BASE_64"],
    is_key_content_base64: true,
    duration: 1200
  )
end