# -- Lanes -- 

lane :testflight do
  load_dotenv('Secrets/.env')
  
  build_app(
    scheme: "GameSession",
    output_directory: "fastlane/build"
  )

  api_key = app_store_connect_api_key(
    key_id: ENV["APPLE_KEY_ID"],
    issuer_id: ENV["APPLE_ISSUER_ID"],
    key_content: ENV["APPLE_KEY_BASE_64"],
    is_key_content_base64: true,
    duration: 1200
  )

  upload_to_testflight(
    api_key: api_key,
    ipa: 'fastlane/build/GameSession.ipa',
    skip_waiting_for_build_processing: true
  )
end

# -- Methods -- 

def load_dotenv(path)
  if File.file?(path)
    sh(path)
  end
end
